### ISSUE TITLE
Security Issue

### ISSUE THREAD

**Issue by elambharathy1** [SAP/sap-customer-data-cloud-toolkit#30]
I like the tool and wants this feature to be embedded within Product. But is it not a security issue that this extension reads the logged in user secret and attaches it with all subsequent CDC calls from client side. Having this credential will give a super access to all customer accounts of this user and literally anything can be done. By this way, I am exposed forever until i reset my credentials.

**Comment by luismarques-io** [comment]
Hi @elambharathy1, the extension has gone through strong security screenings without any issues, we don't save the user credentials anywhere, not even cookies or local storage on the user's machine. 
The credentials are read from the SAP CDC console every time it loads and are only stored in temporary memory for use during the current session. The web browser automatically clears them from memory when you close the page.
