### ISSUE TITLE
Support Address in Schema copy config

### ISSUE THREAD

**Issue by ohados** [SAP/sap-customer-data-cloud-toolkit#41]
we have added a new "address" section that is used by the DQM integration.
we have predefined an OOTB addresses fields for customers to use. They can also add additional fields. 
We of course support multi addresses so customers can collect more than one address form the end-user.
Important to know that even customers that don’t use DQM will have the new addresses section available to use.
You can see it on US1-ST2.

**Comment by bmmsantos** [comment]
The feature was implemented on release 1.7.0
https://github.com/SAP/sap-customer-data-cloud-toolkit/releases/tag/1.7.0
